program vorticity
use modIOHF  ! HYCOM array I/O interface
IMPLICIT NONE
!
!     WIND ARRAYS.
!
      INTEGER, ALLOCATABLE :: MSK(:,:)
      REAL*4,  ALLOCATABLE :: RSCX(:,:),RSCY(:,:)
      REAL*4,  ALLOCATABLE :: ml(:,:)

      REAL*4,  PARAMETER   :: ONEM=1.0

      CHARACTER PREAMBL(5)*79
!
!**********
!*
! 1)  CALCULATE THE CURL OF EXISTING HYCOM WIND STRESS FILES.
!
! 2)  INPUT
!        ON UNIT 10:    .a/.b FORMAT MODEL TAUEWD  FILE, SEE (3).
!        ON UNIT 11:    .a/.b FORMAT MODEL TAUNWD  FILE, SEE (3).
!        ON UNIT 21:    .a/.b FORMAT regional.grid FILE.
!     OUTPUT:
!        ON UNIT 12:    .a/.b FORMAT MODEL CURL    FILE, SEE (4).
!
! 3)  THE INPUT WIND STRESSES HAVE THEIR COMPONENTS ON EITHER
!      EVERY POINT OF THE MODEL'S 'U' AND 'V' GRIDS RESPECTIVELY,
!      OR BOTH ON EVERY POINT OF THE MODEL'S 'P' GRID.  IF ON THE
!      P-GRID, IT IS FIRST INTERPOLATED TO THE U AND V GRIDS AND
!      THEN THE CURL CALCULATED FROM THE STRESSES ON THESE GRIDS.
!
! 4)  THE CURL IS CALCULATED ON THE STREAMFUNCTION-GRID, AS IS
!      NATURAL FOR STRESSES ON THE U AND V GRIDS, AND INTERPOLATED
!      TO THE P-GRID FOR OUTPUT.  THIS MAY REDUCE ACCURACY.
!      ARRAY SIZE IS 'IDM' BY 'JDM', AND THE DATA IS OUTPUT .a/.b
!      FORMAT TOGETHER WITH EITHER (A) THE MONTH, OR (B) THE DAY THE
!      WIND REPRESENTS AND THE INCREMENT IN DAYS TO THE NEXT WIND
!      RECORD.  
!
! 5)  ALAN J. WALLCRAFT,  NRL,  NOVEMBER 2002.
!*
!**********
!
      LOGICAL      PGRID,GLOBAL
      CHARACTER*80 CLINE
      CHARACTER*8,parameter :: FLNM='fort.10A', FLNMO='fort.12A'
      CHARACTER*8,parameter :: FLNMR='fort.21A'
      INTEGER      IDM,JDM,I,IOS,IM1,IP1,J,JM1,JP1,KREC,NREC,IREC,NPAD
      REAL*4       HMINA,HMINB,HMAXA,HMAXB
      REAL*4       XMIN,XMAX
!
! --- MODEL ARRAYS.
!
      CALL XCSPMD(idm,jdm)  !define idm,jdm

      ALLOCATE(  RSCX(IDM,JDM) )
      ALLOCATE(  RSCY(IDM,JDM) )
      ALLOCATE( ml(IDM,JDM) )
!
!     GRID INPUT.
!
!      CALL ZAIOST
!
!      CALL ZHOPNC(21, 'regional.grid.b', 'FORMATTED', 'OLD', 0)

     call RHF(FLNMR,IDM,JDM,10,rscx)
     call RHF(FLNMR,IDM,JDM,11,rscy)
!

      DO I= 1,IDM
        DO J= 1,JDM
          RSCX(I,J) = 1.0/MAX(ONEM,RSCX(I,J)) !1/qscx
          RSCY(I,J) = 1.0/MAX(ONEM,RSCY(I,J)) !1/qscy
        ENDDO
      ENDDO

!     INITIALIZE HYCOM INPUT AND OUTPUT.


     call RHF(FLNM,idm,jdm,6,ml)

      write(6,*) ml(500,500)

!     PROCESS ALL THE WIND RECORDS.

call WHF(FLNMO,idm,jdm,1,ml)
     
END
